### ISSUE TITLE
Unity5: Script missing from gameobject, could not find/create database

### ISSUE THREAD

**Issue by mdragon159** [shreks7/SqliteForUnity#1]
Hello,

I recently tried to clone and test your Unity5 project example. However, in the example itself, it seems the repo is missing a bit of information.
- The "CreateDB" gameobject was missing a script. (In the screenshot below, I assumed it was the "Create Game DB" script, and the values in the screenshot were filled in for me)
- There's an error when trying to access/create the database:
  
  ```
      SQLiteException: Could not open database file: Assets/StreamingAssets/game.db (CannotOpen)
      SqliteForUnity3D.SQLiteConnection..ctor (System.String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks)
      SqliteForUnity3D.ConnectionFactory.Create (System.String address)
  ```

It seems like a pretty darn amazing example, but unfortunately I can only guess that not all the files were committed/pushed to the repo. As for the "can't open database" issue, the particular version of the error above that I pasted is after trying to check the "Reset Database" box.

Best,
Jawad

![screenshot 2015-03-15 12 42 07](https://cloud.githubusercontent.com/assets/8507867/6656943/20d28060-cb11-11e4-9940-0a90b8b42a01.png)

**Comment by shreks7** [comment]
I am not at my desk right now, but can you try creating a directory "StreamingAssets" and try again?

Also for the missing Game Objects , check the prefabs folder. Just drag the corresponding ones into the slot (Level,Chapter btn). 

Will try to fix this, when I am back.

**Comment by mdragon159** [comment]
Ah, that worked quite splendidly. I find it a bit odd that Unity refused to create the "StreamingAssets" folder, but it worked.

I also had to add the appropriate scripts to the prefabs (Level, Chapter buttons) as they were also missing before getting it to work. I was going to commit the files and make a pull request (with the game.db, scene, and prefabs changed), but it's odd- only game.db is showing up. After looking into this more, it seems you're ignoring all .meta files. As far as I can tell, those files are quite important, including for this situation. However, I'll leave it up to you to change the .gitignore (and ultimately to fix this repo issue, as the game.db file isn't necessary to ship with- moreso of your own personal choice).

Either way, I really appreciate all the work done here. Thank you!

**Comment by mdragon159** [comment]
Ah nevermind me about the .gitignore, I forgot to save the scene.... Out of curiosity, what ARE the .meta files for?

Would you like me to do a pull request just to save a little work, and if so, would you like the game.db file included (so a StreamingAssets folder is made) or some other solution? (like a README.txt in that folder itself)

(Also, as a small side note, made the input field much wider so I could actually read the help text)

**Comment by shreks7** [comment]
Thanks for this, you can go ahead and create the pull request with a
StreamingAssets Folder without the .db file. A readme.txt would be great
though.

I will accept the pull request.

Cheers,

Shrey Malhotra

**Comment by mdragon159** [comment]
Sounds great, and just created a pull request with all the changes. Thanks for creating this repo in the first place!

Best,
Jawad Nasser
